<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $item = new \App\Country([ 'name' => 'Afghanistan',                                  'code' => 'AF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Albania',                                      'code' => 'AL' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Algeria',                                      'code' => 'DZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'American Samoa',                               'code' => 'AS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Andorra',                                      'code' => 'AD' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Angola',                                       'code' => 'AO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Anguilla',                                     'code' => 'AI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Antigua and Barbuda',                          'code' => 'AG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Argentina',                                    'code' => 'AR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Armenia',                                      'code' => 'AM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Aruba',                                        'code' => 'AW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Australia',                                    'code' => 'AU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Austria',                                      'code' => 'AT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Azerbaijan',                                   'code' => 'AZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bahamas',                                      'code' => 'BS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bahrain',                                      'code' => 'BH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bangladesh',                                   'code' => 'BD' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Barbados',                                     'code' => 'BB' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Belarus',                                      'code' => 'BY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Belgium',                                      'code' => 'BE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Belize',                                       'code' => 'BZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Benin',                                        'code' => 'BJ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bermuda',                                      'code' => 'BM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bhutan',                                       'code' => 'BT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bolivia',                                      'code' => 'BO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bonaire, Sint Eustatius and Saba',             'code' => 'BQ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bosnia and Herzegovina',                       'code' => 'BA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Botswana',                                     'code' => 'BW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Brazil',                                       'code' => 'BR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Brunei Darussalam',                            'code' => 'BN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Bulgaria',                                     'code' => 'BG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Burkina Faso',                                 'code' => 'BF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Burundi',                                      'code' => 'BI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Cabo Verde',                                   'code' => 'CV' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Cambodia',                                     'code' => 'KH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Cameroon',                                     'code' => 'CM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Canada',                                       'code' => 'CA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Cayman Islands',                               'code' => 'KY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Central African Republic',                     'code' => 'CF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Chad',                                         'code' => 'TD' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Chile',                                        'code' => 'CL' ]); $item->save();
        $item = new \App\Country([ 'name' => 'China',                                        'code' => 'CN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Colombia',                                     'code' => 'CO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Comoros',                                      'code' => 'KM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Congo',                                        'code' => 'CG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Congo, Democratic Republic',                   'code' => 'CD' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Cook Islands',                                 'code' => 'CK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Costa Rica',                                   'code' => 'CR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Côte d`Ivoire',                                'code' => 'CI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Croatia',                                      'code' => 'HR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Cuba',                                         'code' => 'CU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Curaçao',                                      'code' => 'CW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Cyprus',                                       'code' => 'CY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Czech Republic',                               'code' => 'CZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Denmark',                                      'code' => 'DK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Djibouti',                                     'code' => 'DJ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Dominica',                                     'code' => 'DM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Dominican Republic',                           'code' => 'DO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Ecuador',                                      'code' => 'EC' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Egypt',                                        'code' => 'EG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'El Salvador',                                  'code' => 'SV' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Equatorial Guinea',                            'code' => 'GQ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Eritrea',                                      'code' => 'ER' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Estonia',                                      'code' => 'EE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Ethiopia',                                     'code' => 'ET' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Falkland Islands',                             'code' => 'FK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Faroe Islands',                                'code' => 'FO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Fiji',                                         'code' => 'FJ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Finland',                                      'code' => 'FI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'France',                                       'code' => 'FR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'French Guiana',                                'code' => 'GF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'French Polynesia',                             'code' => 'PF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'French Southern Territories',                  'code' => 'TF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Gabon',                                        'code' => 'GA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Gambia',                                       'code' => 'GM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Georgia',                                      'code' => 'GE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Germany',                                      'code' => 'DE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Ghana',                                        'code' => 'GH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Gibraltar',                                    'code' => 'GI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Greece',                                       'code' => 'GR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Grenada',                                      'code' => 'GD' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Guadeloupe',                                   'code' => 'GP' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Guam',                                         'code' => 'GU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Guatemala',                                    'code' => 'GT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Guernsey',                                     'code' => 'GG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Guinea',                                       'code' => 'GN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Guinea-Bissau',                                'code' => 'GW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Guyana',                                       'code' => 'GY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Haiti',                                        'code' => 'HT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Heard Island and McDonald Islands',            'code' => 'HM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Holy See',                                     'code' => 'VA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Honduras',                                     'code' => 'HN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Hong Kong',                                    'code' => 'HK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Hungary',                                      'code' => 'HU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Iceland',                                      'code' => 'IS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'India',                                        'code' => 'IN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Indonesia',                                    'code' => 'ID' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Iran',                                         'code' => 'IR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Iraq',                                         'code' => 'IQ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Ireland',                                      'code' => 'IE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Isle of Man',                                  'code' => 'IM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Israel',                                       'code' => 'IL' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Italy',                                        'code' => 'IT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Jamaica',                                      'code' => 'JM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Japan',                                        'code' => 'JP' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Jersey',                                       'code' => 'JE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Jordan',                                       'code' => 'JO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Kazakhstan',                                   'code' => 'KZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Kenya',                                        'code' => 'KE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Kiribati',                                     'code' => 'KI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Kuwait',                                       'code' => 'KW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Kyrgyzstan',                                   'code' => 'KG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Lao People\'s Democratic Republic',            'code' => 'LA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Latvia',                                       'code' => 'LV' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Lebanon',                                      'code' => 'LB' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Lesotho',                                      'code' => 'LS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Liberia',                                      'code' => 'LR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Libya',                                        'code' => 'LY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Liechtenstein',                                'code' => 'LI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Lithuania',                                    'code' => 'LT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Luxembourg',                                   'code' => 'LU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Macao',                                        'code' => 'MO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Macedonia',                                    'code' => 'MK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Madagascar',                                   'code' => 'MG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Malawi',                                       'code' => 'MW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Malaysia',                                     'code' => 'MY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Maldives',                                     'code' => 'MV' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Mali',                                         'code' => 'ML' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Malta',                                        'code' => 'MT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Marshall Islands',                             'code' => 'MH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Martinique',                                   'code' => 'MQ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Mauritania',                                   'code' => 'MR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Mauritius',                                    'code' => 'MU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Mayotte',                                      'code' => 'YT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Mexico',                                       'code' => 'MX' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Micronesia',                                   'code' => 'FM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Moldova',                                      'code' => 'MD' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Monaco',                                       'code' => 'MC' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Mongolia',                                     'code' => 'MN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Montenegro',                                   'code' => 'ME' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Montserrat',                                   'code' => 'MS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Morocco',                                      'code' => 'MA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Mozambique',                                   'code' => 'MZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Myanmar',                                      'code' => 'MM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Namibia',                                      'code' => 'NA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Nauru',                                        'code' => 'NR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Nepal',                                        'code' => 'NP' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Netherlands',                                  'code' => 'NL' ]); $item->save();
        $item = new \App\Country([ 'name' => 'New Caledonia',                                'code' => 'NC' ]); $item->save();
        $item = new \App\Country([ 'name' => 'New Zealand',                                  'code' => 'NZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Nicaragua',                                    'code' => 'NI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Niger',                                        'code' => 'NE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Nigeria',                                      'code' => 'NG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Niue',                                         'code' => 'NU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Norfolk Island',                               'code' => 'NF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'North Korea',                                  'code' => 'KP' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Northern Mariana Islands',                     'code' => 'MP' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Norway',                                       'code' => 'NO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Oman',                                         'code' => 'OM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Pakistan',                                     'code' => 'PK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Palau',                                        'code' => 'PW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Palestine',                                    'code' => 'PS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Panama',                                       'code' => 'PA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Papua New Guinea',                             'code' => 'PG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Paraguay',                                     'code' => 'PY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Peru',                                         'code' => 'PE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Philippines',                                  'code' => 'PH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Pitcairn',                                     'code' => 'PN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Poland',                                       'code' => 'PL' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Portugal',                                     'code' => 'PT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Puerto Rico',                                  'code' => 'PR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Qatar',                                        'code' => 'QA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Réunion',                                      'code' => 'RE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Romania',                                      'code' => 'RO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Russia',                                       'code' => 'RU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Rwanda',                                       'code' => 'RW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Saint Barthélemy',                             'code' => 'BL' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Saint Kitts and Nevis',                        'code' => 'KN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Saint Lucia',                                  'code' => 'LC' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Saint Martin',                                 'code' => 'MF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Saint Pierre and Miquelon',                    'code' => 'PM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Saint Vincent and the Grenadines',             'code' => 'VC' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Samoa',                                        'code' => 'WS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'San Marino',                                   'code' => 'SM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Sao Tome and Principe',                        'code' => 'ST' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Saudi Arabia',                                 'code' => 'SA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Senegal',                                      'code' => 'SN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Serbia',                                       'code' => 'RS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Seychelles',                                   'code' => 'SC' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Sierra Leone',                                 'code' => 'SL' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Singapore',                                    'code' => 'SG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Sint Maarten',                                 'code' => 'SX' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Slovakia',                                     'code' => 'SK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Slovenia',                                     'code' => 'SI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Solomon Islands',                              'code' => 'SB' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Somalia',                                      'code' => 'SO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'South Africa',                                 'code' => 'ZA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'South Korea',                                  'code' => 'KR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'South Sudan',                                  'code' => 'SS' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Spain',                                        'code' => 'ES' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Sri Lanka',                                    'code' => 'LK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Sudan',                                        'code' => 'SD' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Suriname',                                     'code' => 'SR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Svalbard and Jan Mayen',                       'code' => 'SJ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Swaziland',                                    'code' => 'SZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Sweden',                                       'code' => 'SE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Switzerland',                                  'code' => 'CH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Syrian Arab Republic',                         'code' => 'SY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Taiwan',                                       'code' => 'TW' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Tajikistan',                                   'code' => 'TJ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Tanzania',                                     'code' => 'TZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Thailand',                                     'code' => 'TH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Timor-Leste',                                  'code' => 'TL' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Togo',                                         'code' => 'TG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Tokelau',                                      'code' => 'TK' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Tonga',                                        'code' => 'TO' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Trinidad and Tobago',                          'code' => 'TT' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Tunisia',                                      'code' => 'TN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Turkey',                                       'code' => 'TR' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Turkmenistan',                                 'code' => 'TM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Turks and Caicos Islands',                     'code' => 'TC' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Tuvalu',                                       'code' => 'TV' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Uganda',                                       'code' => 'UG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Ukraine',                                      'code' => 'UA' ]); $item->save();
        $item = new \App\Country([ 'name' => 'United Arab Emirates',                         'code' => 'AE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'United Kingdom',                               'code' => 'GB' ]); $item->save();
        $item = new \App\Country([ 'name' => 'United States',                                'code' => 'US' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Uruguay',                                      'code' => 'UY' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Uzbekistan',                                   'code' => 'UZ' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Vanuatu',                                      'code' => 'VU' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Venezuela',                                    'code' => 'VE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Vietnam',                                      'code' => 'VN' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Virgin Islands (British)',                     'code' => 'VG' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Virgin Islands (US)',                          'code' => 'VI' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Wallis and Futuna',                            'code' => 'WF' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Western Sahara',                               'code' => 'EH' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Yemen',                                        'code' => 'YE' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Zambia',                                       'code' => 'ZM' ]); $item->save();
        $item = new \App\Country([ 'name' => 'Zimbabwe',                                     'code' => 'ZW' ]); $item->save();
    }
}
